config/routes.rb
Rails.application.routes.draw do
  get 'error_pages/not_found_error'

  get 'error_pages/internal_error'

  get 'error_pages/misc_error'

  resources :posts

  root 'static_pages#home'

  get 'static_pages/directory'

  get 'static_pages/contribute'

  get 'static_pages/contact'

  get 'static_pages/about'
  get 'static_pages/render_dir'
  get 'static_pages/feedback'

  get 'static_pages/news'

  devise_for :users
  get 'users/show'
  get 'users/profile'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @ap=Post.where(:user_id => 1).first(3)
    @up=Post.where.not(:user_id => 1).first(1)
    @ap=@ap+@up
  end

  def directory
    @curr_year = Time.now.year
    if params[:year_req].present?
      all_users = User.where(alumni: true, YOL: params[:year_req])
      @curr_year = params[:year_req]
    else
      all_users = User.where(alumni: true, YOL: @curr_year)
      if all_users.empty?
        all_users = User.where(alumni: true, YOL: @curr_year-1)
        @curr_year -= 1
      end
    end
    @users=all_users.paginate(page: params[:page], :per_page => 21).order(name: :asc)
  end

  def render_dir
    redirect_to :action => "directory", :year_req => params[:year_req]
  end

  def contribute
  end

  def contact
  end

  def about
  end

  def feedback
  end

  def news
    @adp=User.first.posts.paginate(page: params[:page], :per_page => 5)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>Content to be filled by the institute</p>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p>Faculty Coordinator</p>

app/views/static_pages/contribute.html.erb
<h1>Contribute</h1>
<br>
<p>Give back to your institute</p>
<p> Insert form here </p>

app/views/static_pages/directory.html.erb
<div class="pull-right">
    <form class="form-inline" action="/static_pages/render_dir" accept-charset="UTF-8" method="get">
    <br><br><br>
        <input name="utf8" type="hidden" value="&#x2713;" />
        <div class="form-group">
            <label for="year_req" class="control-label">Select Year</label>

            <%= select_tag :year_req, options_for_select((2012..Time.now.year).step(1).to_a.map{|s| ["#{s}", s]},@curr_year),:class => 'form-control' %>
        </div>
        <button type="submit" class="btn-sm btn-primary">GO</button>
    </form>
</div>
<h1 class="page-header"> Alumni: Batch of <%= @curr_year %> </h1>
<% if @users.any? %>
<%= will_paginate @users %>
<% @users.each do |x| %>
<div class="card hovercard container" style="width:30%;height:120px;float:left;margin:10px">
    <% if x.avatar.url.present? %>
    <%= image_tag x.avatar.url,class: "pull-right ",width: "84px",height: "84px" %>
    <% end %>
    <div class="info">
        <h3 class="title">
        <% if user_signed_in? %>
            <%= link_to x.name,users_profile_path(id: x.id) %>
        <% else %>
            <%= x.name %>
        <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <% if x.alumni %>
            <%= x.email %> 
        <% else %>
            <%= x.current_designation %> @ <%= x.company_or_institution %>
        <% end %>
    </div>
</div>
<% end %>
<%else %>
<h1 style="color:#A0A0A0">No Records</h1>
<% end %>

app/views/static_pages/feedback.html.erb
<h1>Feedback</h1>
<p>We value your feedback a lot and we'll make sure we read it thoroughly and throw it in the nearest bin</p>

app/views/static_pages/home.html.erb
<div class="row">
<div class="col-lg-12" id="home-img">
<h1 style="color:white;font-size:60px;font-weight:bold;font-family:'aaargh';">
Welcome to IIITD Alumni Portal
</h1>
</div>
</div>
<br><br>
<% if @ap.any? %>
<div class="row"><div class="col-lg-7">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% (0..@ap.count-1).each do |i| %>
    <li data-target="#myCarousel" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner" role="listbox">
    <% @ap.each do |post| %>
    <div class="item<%= ' active'if post == @ap.first %>">
      <center><%= image_tag(post.avatar.present? ? post.avatar.url : "blog-placeholder.jpg",style: "max-height:600px;max-width:600px;opacity:80%") %><center/>
      <div class="carousel-caption">
        <h3><%= post.title %></h3>
        <p><%= truncate(post.content, :length => 50) %>... <br><br> <%= link_to "Read More",post_path(post),:class => "btn btn-sm btn-info" %></p>
      </div>
    </div>
    <% end %>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="fa fa-chevron-left glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="fa fa-chevron-right glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
</div>
<div class="col-lg-1">
&nbsp;
</div>

</div>
<% else %>  
<center><h1>No News / Posts to show</h1></center>
<% end %>

app/views/static_pages/news.html.erb
<h1 align="left" class="page-header"> News </h1>
<div class="row">
  <div class="col-lg-8">
    <% if @adp.any? %>
  <%= will_paginate @adp %>

      <% @adp.each do |post| %>
        <div class="container" style="border-bottom: 2px solid gray;max-width:800px;padding:20px;">
        <div class="row">
          <div class="col-md-6" style="text-align:center">
            <%= image_tag(post.avatar.present? ? post.avatar.url : "blog-placeholder.jpg",style: "max-height:280px;max-width:280px;") %>
          </div>
          <div class="col-md-6">
            <h1 style="font-weight:bold;"><%= post.title %></h1>
            <font color="gray">
               <%= time_ago_in_words(post.created_at) %> ago<br/><br/>
            </font>
            <td>
              <%= truncate(post.content, :length => 150) %>... | <%= link_to "Read More",post_path(post) %>
            </td>
            <% if user_signed_in? %>
            <% if current_user.id == 1 %>
            <br><br>
              <%= link_to "Edit",edit_post_path(post),class: 'btn-sm btn-info'%> <%= link_to "Delete", post_path(post), method: :delete,class: 'btn-sm btn-danger', data: {confirm: 'Are you sure?'}%>
            <% end %><% end %>
          </div>
        </div>
        </div>
      <% end -%>
        <%= will_paginate @adp %>
    <% else %>
      <h1 style="color:#A0A0A0;">No News yet</h1>
    <% end %>
  </div>
</div>