config/routes.rb
Rails.application.routes.draw do
  get 'error_pages/not_found_error'

  get 'error_pages/internal_error'

  get 'error_pages/misc_error'

  resources :posts

  root 'static_pages#home'

  get 'static_pages/directory'

  get 'static_pages/contribute'

  get 'static_pages/contact'

  get 'static_pages/about'
  get 'static_pages/render_dir'
  get 'static_pages/feedback'

  get 'static_pages/news'

  devise_for :users
  get 'users/show'
  get 'users/profile'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :YOJ, presence: true, format: { with: /20[0123456789]\d/ } 
  validates :YOL, presence: true, format: { with: /20[0123456789]\d/ }
  validates :pursued, presence: true
  validates :rollno, presence: true, uniqueness: true
  validates :phone, length: {is: 10} #Flawed
  validates :ld_url, :allow_blank => true, format: { with: /(ftp|http|https):\/\/?((www|\w\w)\.)?linkedin.com(\w+:{0,1}\w*@)?(\S+)(:([0-9])+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/ }
  validates_processing_of :avatar
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
  	@user = current_user
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:YOJ) %></th>
      <th><%= model_class.human_attribute_name(:YOL) %></th>
      <th><%= model_class.human_attribute_name(:alumni) %></th>
      <th><%= model_class.human_attribute_name(:pursued) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:current_designation) %></th>
      <th><%= model_class.human_attribute_name(:company_or_institution) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:blog_url) %></th>
      <th><%= model_class.human_attribute_name(:ld_url) %></th>
      <th><%= model_class.human_attribute_name(:rollno) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= @users.each do |x| %>
      <tr>
        <td><%= link_to x.id, user_path(x) %></td>
        <td><%= x.name %></td>
        <td><%= x.YOJ %></td>
        <td><%= x.YOL %></td>
        <td><%= x.alumni %></td>
        <td><%= x.pursued %></td>
        <td><%= x.description %></td>
        <td><%= x.current_designation %></td>
        <td><%= x.company_or_institution %></td>
        <td><%= x.email %></td>
        <td><%= x.encrypted_password %></td>
        <td><%= x.reset_password_token %></td>
        <td><%= x.reset_password_sent_at %></td>
        <td><%= x.remember_created_at %></td>
        <td><%= x.current_sign_in_at %></td>
        <td><%= x.last_sign_in_at %></td>
        <td><%= x.current_sign_in_ip %></td>
        <td><%= x.last_sign_in_ip %></td>
        <td><%= x.blog_url %></td>
        <td><%= x.ld_url %></td>
        <td><%= x.rollno %></td>
        <td><%= x.phone %></td>
        <td><%= x.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(x), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(x),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/profile.html.erb
<div class="row" style="padding:5px;">
<div class="col-lg-3" style="text-align:center;padding-top:15px;">
<h3><%=t '.title', :default => @user.name.titleize %></h3>
<br/>
  <%= image_tag @user.avatar.url.present? ? @user.avatar.url : "user-placeholder.png" ,style: "max-width:200px;max-height:200px" %> <br/><br/>
  <% if @user.alumni %>
    <div style="width:100px;margin:0 auto">
      <i>  <%= @user.pursued %> Student from <%= @user.YOJ %> to <%= @user.YOL %></i>
    </div>
    <br/>
  <% end %>
  <div style="padding:2px;border:1px solid gray;border-radius:4px;width:150px;margin:0 auto;">
    <% if @user.email.present? %> <%= link_to "mailto:"+@user.email,class: "btn-sm btn-default"  do %><i class="fa fa-envelope" style="font-size:25px"></i><% end %> <% end %>
    <% if @user.ld_url.present? %><%= link_to @user.ld_url,class: "btn-sm btn-default"  do %><i class="fa fa-linkedin" style="font-size:25px"></i><% end %> <% end %>
    <% if @user.blog_url.present? %><%= link_to @user.blog_url,class: "btn-sm btn-default"  do %><i class="fa fa-rss-square" style="font-size:25px"></i><% end %> <% end %>
  </div>
  <br/>
 
</div>
<div class="col-lg-9" style="border-left:1px solid #F0F0F0;">
<br/>
<br/>
<div class="panel panel-default">
    <div class="panel-body">
        <%= @user.description.present? ? @user.description : "No Description Available" %>
    </div>
</div>
<dl class="dl-horizontal panel panel-default panel-body">
  <dt><strong><%= "Currently" %>:</strong></dt>
  <dd><%= @user.current_designation %></dd>
  <dt><strong><%= "Company/Institution" %>:</strong></dt>
  <dd><%= @user.company_or_institution %></dd>
  <dt><strong><%= "E-mail" %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= "Roll number" %>:</strong></dt>
  <dd><%= @user.rollno %></dd>
  <dt><strong><%= "Phone" %>:</strong></dt>
  <dd><%= @user.phone %></dd>
</dl>
<% if @user.posts.any? %>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Blog Posts</h3>
    </div>
    <div class="panel-body" style="padding:0px">
        <table class="table table-striped table-hover ">
        <tbody>
        <% @user.posts.each do |post| %>
          <tr><td><%= link_to post.title, post_path(post) %> <%= time_ago_in_words(post.created_at) %></td></tr>
        <% end %>
        </tbody>
        </table>
    </div>
</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row" style="padding:5px;">
<div class="col-lg-3" style="text-align:center;padding-top:15px;">
<h3><%=t '.title', :default => @user.name.titleize %></h3>
<br/>
  <%= image_tag @user.avatar.url.present? ? @user.avatar.url : "user-placeholder.png" ,style: "max-width:200px;max-height:200px" %> <br/><br/>
  <% if @user.alumni %>
    <div style="width:100px;margin:0 auto">
      <i>  <%= @user.pursued %> Student from <%= @user.YOJ %> to <%= @user.YOL %></i>
    </div>
    <br/>
  <% end %>
  <div style="padding:2px;border:1px solid gray;border-radius:4px;width:150px;margin:0 auto;">
    <% if @user.email.present? %> <%= link_to "mailto:"+@user.email,class: "btn-sm btn-default"  do %><i class="fa fa-envelope" style="font-size:25px"></i><% end %> <%end %>
    <% if @user.ld_url.present? %><%= link_to @user.ld_url,class: "btn-sm btn-default"  do %><i class="fa fa-linkedin" style="font-size:25px"></i><% end %> <% end %>
    <% if @user.blog_url.present? %><%= link_to @user.blog_url,class: "btn-sm btn-default"  do %><i class="fa fa-rss-square" style="font-size:25px"></i><% end %> <% end %>
  </div>
  <br/>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_registration_path(@user), :class => 'btn btn-info' %>
 
</div>
<div class="col-lg-9" style="border-left:1px solid #F0F0F0;">
<br/>
<br/>
<div class="panel panel-default">
    <div class="panel-body">
        <%= @user.description.present? ? @user.description : "No Description Available" %>
    </div>
</div>
<dl class="dl-horizontal panel panel-default panel-body">
  <dt><strong><%= "Currently" %>:</strong></dt>
  <dd><%= @user.current_designation %></dd>
  <dt><strong><%= "Company/Institution" %>:</strong></dt>
  <dd><%= @user.company_or_institution %></dd>
  <dt><strong><%= "E-mail" %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= "Roll number" %>:</strong></dt>
  <dd><%= @user.rollno %></dd>
  <dt><strong><%= "Phone" %>:</strong></dt>
  <dd><%= @user.phone %></dd>
</dl>
<% if @user.posts.any? %>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Blog Posts<%= link_to "Write new post",new_post_path, class: "pull-right" %></h3>
    </div>
    <div class="panel-body" style="padding:0px">
        <table class="table table-striped table-hover ">
        <tbody>
        <% @user.posts.each do |post| %>
          <tr><td><%= link_to post.title, post_path(post) %> 
          <%= time_ago_in_words(post.created_at) %>
          </td></tr>
        <% end %>
        </tbody>
        </table>
    </div>
</div>
<% else %>
<%= link_to "Write new post",new_post_path, class: "btn btn-primary pull-right" %>
<% end %>
</div>
</div>