config/routes.rb
Rails.application.routes.draw do
  get 'error_pages/not_found_error'

  get 'error_pages/internal_error'

  get 'error_pages/misc_error'

  resources :posts

  root 'static_pages#home'

  get 'static_pages/directory'

  get 'static_pages/contribute'

  get 'static_pages/contact'

  get 'static_pages/about'
  get 'static_pages/render_dir'
  get 'static_pages/feedback'

  get 'static_pages/news'

  devise_for :users
  get 'users/show'
  get 'users/profile'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">IIITD Alumni</a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to static_pages_news_path do %>
                    <i class="fa fa-newspaper-o"></i> News
                    <% end %>
                </li>
                <li class="dropdown"><a href="#" data-target="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-rss"></i> Blog</a>
                    <ul class="dropdown-menu">
                        <li><%= link_to new_post_path do %>
                        <i class="mdi-content-create"></i> Write new post<% end %>
                        </li>
                        <li><%= link_to posts_path do %>
                        <i class="mdi-av-my-library-books"></i> See All posts
                        <% end %>
                        </li>
                    </ul></li>
                <li>
                <li><%= link_to static_pages_directory_path do %>
                    <i class="mdi-communication-contacts"></i> Directory
                    <% end %>
                </li>
                <li><%= link_to static_pages_contribute_path do %>
                    <i class="fa fa-university"></i> Give Back
                    <% end %>
                </li>
                <li class="dropdown">
                    <a href="#" data-target="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Account</a>
                    <ul class="dropdown-menu">
                        <li><%= link_to users_show_path do%>
                        <i class="fa fa-info-circle"></i> Profile <% end %>
                        </li>
                        <li><%= link_to edit_registration_path(current_user) do %>
                            <i class="fa fa-cog"></i> Settings
                            <% end %>
                        </li>
                        <li class="divider"></li>
                        <li><%= link_to destroy_user_session_path, method: "delete" do %>
                            <i class="fa fa-sign-out"></i> Log out
                            <% end %>
                        </li>
                    </ul>
                </li>
                    
            <% else %>
                <li><%= link_to static_pages_news_path do %>
                    <i class="fa fa-newspaper-o"></i> News
                    <% end %>
                </li>
                <li><%= link_to posts_path do %>
                <i class="fa fa-rss"></i> Blog<% end %>
                </li>
                <li><%= link_to static_pages_directory_path do %>
                    <i class="mdi-communication-contacts"></i> Directory
                    <% end %>
                </li>
                <li><%= link_to static_pages_contribute_path do %>
                    <i class="fa fa-university"></i> Give Back
                    <% end %>
                </li>
                <li><%= link_to new_session_path(:user) do %>
                <i class="fa fa-sign-in"></i> Login<% end %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-dismissable alert-<%= alertSanitizer(key) %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul style="list-style:none;">
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>IIITD Alumni Portal</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
    <div class="footer" style="text-align:center;color:#A0A0A0;">
    <hr/>
    	<%= image_tag("iiitd-grayscale.png",:style => "opacity:0.5;height:40px;") %><br/>
      <br>
        <%= link_to 'Home',root_path %> | 
        <%= link_to 'Top of Page',"#" %> | 
        <%= link_to 'About',static_pages_about_path %> |
        <%= link_to 'Contact',static_pages_contact_path %> | <%= link_to 'Main website',"http://www.iiitd.ac.in/" %>
        <br/> © IIIT-Delhi, 2015 
    </div>
	</body>
</html>